### ISSUE TITLE
如何解RTSP码流？有相关的例子么？

### ISSUE THREAD

**Issue by gjtjx** [sipeed/axpi_bsp_sdk#1]

**Comment by junhuanchen** [comment]
解码器是 [vdec](https://github.com/sipeed/axpi_bsp_sdk/tree/main/msp/sample/vdec)

**Comment by junhuanchen** [comment]
https://github.com/sipeed/axpi_bsp_sdk/blob/main/docs/09%20-%20AX%20VDEC%20API%20%E6%96%87%E6%A1%A3.pdf

**Comment by gjtjx** [comment]
多谢
